Deploy
Luchy-B/budget pull request #2
Opened 2023-07-19 14:25 UTC by Luchy-B

Requirements Met

- Splash screen
  -  A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  -  The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.
 
- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
      - [ ]  name (mandatory)
      - [ ]   amount (mandatory)
      - [ ]   categories (mandatory at least one)

  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.

2023-07-19 17:33 UTC, mukhammadrizooff requested changes
Hi @Luchy-B, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 17:33 UTC, mukhammadrizooff commented on spec/requests/operations_spec.rb
> +end
- [ ] [REQUIRED] Good job so far! Kindly, this part `failed` with  `ActionView::Template::Error:`, please fix this `spec` 🙏🏼 

![image](https://github.com/Luchy-B/budget/assets/63915024/18826312-a800-4cfd-9b8a-18b4cd4fbfd0)

2023-07-19 21:01 UTC, Luchy-B commented on spec/requests/operations_spec.rb
> +end
Thank you for the review. Test fixed

2023-07-19 21:52 UTC, Whoistolu commented on spec/requests/operations_spec.rb
> +end
- You have a done a great job resolving the test.

2023-07-19 22:07 UTC, Whoistolu requested changes
Hi @Luchy-B 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 22:07 UTC, Whoistolu commented on app/views/categories/index.html.erb
> +</div>
- [ ] [REQUIRED] Kindly check the recommendation the previous reviewer dropped on the review summary where he stated that you need to stick to the Behance design color, typography: font face, size, and weight, Layout: composition, and space between elements. Kindly ensure that the nav bar, the Add new category button, and the application background has the same color as recommended in the Behance design. Kindly implement this for the rest of the pages as well to enhance uniformity.
Take a look at this:

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
<img width="308" alt="Screenshot 2023-07-19 at 22 52 49" src="https://github.com/Luchy-B/budget/assets/58692590/1f19070d-603b-4036-b42d-b470b5a76db8"> | <img width="357" alt="Screenshot 2023-07-19 at 23 02 49" src="https://github.com/Luchy-B/budget/assets/58692590/ca4f72e3-07ce-41f7-90a1-19ed139fe53a">

2023-07-20 09:47 UTC, julie-ify approved these changes
Hi @Luchy-B,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 09:49 UTC, Luchy-B commented
Thank you for the review

2023-07-20 09:50 UTC, merged